Fix CSV metadata
scientist-softserv/adventist-dl pull request #268
Opened 2023-02-16 00:57 UTC by kirkkwang

In `bulkrax.rb` had `part` instead of `part_of` so the fields were not
mapping correctly, a test was added to the CsvEntrySpec.  Curious, since
in the OAI parser there is a `part` field as well as a `part_of` field.
When checking on the model, I didn't see a `part` property and only a
`part_of` property.

The `rights_statement` was not being rendered properly on the view
template and that has been corrected.

2023-02-16 20:28 UTC, jeremyf commented on config/initializers/bulkrax.rb
> +        'part_of' => { from:  ['relation.isPartOf'] },
We should hold off on this.  What we have is adequate and we can clarify later.  It's possible we need both the deleted line and the added line, but we'll know more once we resolve the question.

2023-02-16 20:56 UTC, ShanaLMoore requested changes
requesting changes per Jeremy's feedback

2023-02-16 20:57 UTC, ShanaLMoore commented on config/initializers/bulkrax.rb
> +        'part_of' => { from:  ['relation.isPartOf'] },
oh actually, we need both lines. I added both because different work types have either part or part_of. so we needed both

2023-02-16 22:22 UTC, kirkkwang commented on config/initializers/bulkrax.rb
> +        'part_of' => { from:  ['relation.isPartOf'] },
Added `part` back in!

2023-02-16 22:58 UTC, ShanaLMoore approved these changes

2023-02-17 14:54 UTC, jeremyf commented on app/views/hyrax/base/_attribute_rows.html.erb
> -<%= presenter.attribute_to_html(:rights_statement) %>
Great catch!

2023-02-17 14:54 UTC, jeremyf commented on spec/models/bulkrax/csv_entry_spec.rb
> +      expect(entry.parsed_metadata.fetch('part_of')).to eq ["Center for Adventist Research Photograph Collection"]
Thank you for adding this spec!

2023-02-17 14:54 UTC, jeremyf approved these changes

2023-02-17 14:56 UTC, merged