i345 - Update IIIF Manifest labels to show titles
scientist-softserv/adventist-dl pull request #364
Opened 2023-04-06 23:10 UTC by kirkkwang

ref #345 

Prior to this commit, the IIIF Manifest's canvas label is based on the record's label which is actually the filename.  This is not desirable because the filename is often times not human-readable.  This commit will instead instead the file set's parent work's title and use that instead as the label.

Before:
![image](https://user-images.githubusercontent.com/19597776/230509890-ae12ec4a-f8d4-40b8-8ca3-9b75aaa85354.png)

After:
![image](https://user-images.githubusercontent.com/19597776/230509756-cbbbb5ba-55cc-47f5-854d-6aca9a7f61bf.png)

2023-04-06 23:14 UTC, laritakr commented
This is a bit misleading with the changes to the way we do child work titles.

Updated examples coming up...

2023-04-06 23:16 UTC, kirkkwang commented
> This is a bit misleading with the changes to the way we do child work titles.
> 
> Updated examples coming up...

oh nooo you're right, we wouldn't have such nice titles

2023-04-07 14:08 UTC, ShanaLMoore commented
Just noting for QA, the way that this is implemented requires another staging reindex.

2023-04-07 14:12 UTC, ShanaLMoore commented
Do you think this is something everyone would want (and should go into iiif_print instead?)

2023-04-07 14:14 UTC, laritakr commented
> Do you think this is something everyone would want (and should go into iiif_print instead?)

I think we want to consider doing it like we did child work title, as a lambda, so everyone can configure their own. This implementation would be confusing for organizations that have more than one PDF splitting, since it uses the parent work's title.

2023-04-07 15:33 UTC, jeremyf commented on app/indexers/hyrax/file_set_indexer.rb
> +        page_number = parent.title.first.match(/Page \d+/)&.[](0)
If we don't have a page number, it seems like we shouldn't check the work_title (which could be expensive)

Consider some short-circuiting logic instead.

2023-04-07 15:33 UTC, jeremyf requested changes
See comments

2023-04-07 20:31 UTC, jeremyf commented on app/indexers/hyrax/file_set_indexer.rb
> +        page_number = parent_title[/Page \d+/]
Could you leave a comment as to why this?  Where's this magic regex coming from?  How will future us debug this when we change our title function?

2023-04-07 20:54 UTC, jeremyf approved these changes

2023-04-08 13:22 UTC, merged